# This is a sample pod definition for using SecretProviderClass and service-principal to access Key Vault
kind: Pod
apiVersion: v1
metadata:
  name: nginx-secrets-store-inline
spec:
  containers:
  - image: cpeobsacr.azurecr.io/obs-logging/bitnami/nginx:1.19.1
    name: nginx
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "obs-tls"
        nodePublishSecretRef:                       # Only required when using service principal mode
          name: ac-eng-cpe-spn-devops-001-secrets                 # Only required when using service principal mode
