apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: obs-tls
spec:
  provider: azure
  secretObjects:                                                    # secretObjects defines the desired state of synced K8s secret objects
  - secretName: nginx-ingress-secret-csi                            # CPE Team managed block - DONOT CHANGE
    type: kubernetes.io/tls
    data: 
    - objectName: aks-crd-obs-crd-com
      key: tls.key
    - objectName: aks-crd-obs-crd-com
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    keyvaultName: it-kv-001-int-eastus                              # the name of the KeyVault
    objects: |
      array:
        - |
          objectName: aks-crd-obs-crd-com
          objectType: secret        
    resourceGroup: "it-rg-ntw-001-int-eastus"                       # CPE Team managed setting - DONOT CHANGE
    subscriptionId: "3dc6e706-990f-4ae7-9e84-f23d847c948b"          # CPE Team managed setting - DONOT CHANGE
    tenantId: "cbf6410b-fe4c-4b4c-8420-3f69a6ce199e"                # CPE Team managed setting - DONOT CHANGE
