apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: obs-tls
spec:
  provider: azure
  secretObjects:                                                    # secretObjects defines the desired state of synced K8s secret objects
  - secretName: nginx-ingress-secret-csi                            # CPE Team managed block - DONOT CHANGE
    type: kubernetes.io/tls
    data: 
    - objectName: wildcard-ops-crd-com-2022
      key: tls.key
    - objectName: wildcard-ops-crd-com-2022
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    keyvaultName: agrid-07-p1-hub-kv-001                              # the name of the KeyVault
    objects: |
      array:
        - |
          objectName: wildcard-ops-crd-com-2022
          objectType: secret        
    resourceGroup: "agrid-07-p1-sr-hub-rg-001"                       # CPE Team managed setting - DONOT CHANGE
    subscriptionId: "fd435da3-f7ad-4681-b1fe-2903899c05a0"          # CPE Team managed setting - DONOT CHANGE
    tenantId: "f7d9f3f1-3841-4bfc-9cd4-c0e1964b5f86"                # CPE Team managed setting - DONOT CHANGE
