apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: obs-tls
spec:
  provider: azure
  secretObjects:                                                    # secretObjects defines the desired state of synced K8s secret objects
  - secretName: nginx-ingress-secret-csi                            # CPE Team managed block - DONOT CHANGE
    type: kubernetes.io/tls
    data: 
    - objectName: agrid-06-e1-obs-crd-com
      key: tls.key
    - objectName: agrid-06-e1-obs-crd-com
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    keyvaultName: agrid-06-e1-hub-kv-001                              # the name of the KeyVault
    objects: |
      array:
        - |
          objectName: agrid-06-e1-obs-crd-com
          objectType: secret        
    resourceGroup: "agrid-06-e1-sr-hub-rg-001"                       # CPE Team managed setting - DONOT CHANGE
    subscriptionId: "9db93dfd-6382-4fe2-8fe6-9d2b4d79e1db"          # CPE Team managed setting - DONOT CHANGE
    tenantId: "cbf6410b-fe4c-4b4c-8420-3f69a6ce199e"                # CPE Team managed setting - DONOT CHANGE
